baseURL = 'https://myblog.cazmura.workers.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-bearblog'

[params]
  mainSections = ["blog"]
  hideMadeWithLine = true
  description = "ブログの説明をここに書く"
  images = ["images/og-default.png"]